
let libros = [ 
{
    titulo:"La Sirenita",
    autor:"Hans Christian Andersen",
    genero:"Ficcion",
    idioma:"Español",
    precio:15.000,
    formato:"Tapa dura",
    isbn:"29788478888566",
    descripcion:"La historia de Ariel, una sirena que sueña con vivir en tierra firme.",
    estado:"Nuevo",
    ubicacion:"Los Angeles, Estados Unidos",
    fecha_publicacion:"Junio 1837",
    editorial:"Disney Press",
    paginas: 48,
    dimensiones:"8.5 x 0.5 x 10 pulgadas" ,
    peso:"1.0 libras"

},
{

    titulo: "El Rey León",
    autor: "Walt Disney Company",
    genero: "Ficción",
    idioma: "Español",
    precio: 14.50,
    formato: "Tapa dura",
    isbn: "9788444142579",
    descripcion: "La historia de Simba, un joven león que lucha por reclamar su lugar como rey de la selva.",
    estado: "Nuevo",
    ubicacion: "Orlando, Estados Unidos",
    fecha_publicacion: "Junio 1994",
    editorial: "Editorial Planeta",
    paginas: 64,
    dimensiones: "9.2 x 0.5 x 9 pulgadas",
    peso: "1.2 libras"
},
{

    titulo: "Frozen: Una aventura de Olaf",
    autor: "Disney Book Group",
    genero: "Ficción",
    idioma: "Español",
    precio: 29.900,
    formato: "Tapa blanda",
    isbn: "9781368002509",
    descripcion: "La historia de Olaf, el simpático muñeco de nieve, en una aventura congelada.",
    estado: "Nuevo",
    ubicacion: "Arendelle, Reino de Hielo",
    fecha_publicacion: "Noviembre 2013",
    editorial: "Disney Press",
    paginas: 32,
    dimensiones: "8 x 0.2 x 8 pulgadas",
    peso: "4.8 libras"
},
{

        titulo: "La Bella y la Bestia",
        autor: "Gabrielle-Suzanne Barbot de Villeneuve",
        genero: "Ficción",
        idioma: "Español",
        precio: 12.99,
        formato: "Tapa dura",
        isbn: "9781484781001",
        descripcion: "La historia de Bella, una joven que se enamora de una bestia encantada.",
        estado: "Nuevo",
        ubicacion: "Paris, Francia",
        fecha_publicacion: "Octubre 1756",
        editorial: "Disney Press",
        paginas: 72,
        dimensiones: "8.5 x 0.5 x 11 pulgadas",
        peso: "1.1 libras"
    
},
 {

    titulo: "Blancanieves y los siete enanitos",
    autor: "Hermanos Grimm",
    genero: "Ficción",
    idioma: "Español",
    precio: 11.50,
    formato: "Tapa dura",
    isbn: "9781484781018",
    descripcion: "La clásica historia de Blancanieves y su encuentro con los siete enanitos.",
    estado: "Nuevo",
    ubicacion: "Berlín, Alemania",
    fecha_publicacion: "1812",
    editorial: "Disney Press",
    paginas: 64,
    dimensiones: "8.5 x 0.5 x 11 pulgadas",
    peso: "1.3 libras"
},
{

    titulo: "Mickey Mouse: En busca del tesoro perdido",
    autor: "Walt Disney Company",
    genero: "Aventura",
    idioma: "Español",
    precio: 8.99,
    formato: "Tapa blanda",
    isbn: "9788416387983",
    descripcion: "Mickey y sus amigos se embarcan en una emocionante búsqueda de un tesoro escondido.",
    estado: "Nuevo",
    ubicacion: "Los Angeles, Estados Unidos",
    fecha_publicacion: "Agosto 2009",
    editorial: "Editorial Planeta",
    paginas: 48,
    dimensiones: "8 x 0.2 x 8 pulgadas",
    peso: "4.8 onzas"
}, 
{

    titulo: "Toy Story: La aventura de Buzz Lightyear",
    autor: "Disney Book Group",
    genero: "Ficción",
    idioma: "Español",
    precio: 7.99,
    formato: "Tapa dura",
    isbn: "9788499518982",
    descripcion: "Buzz Lightyear se embarca en una misión para salvar a sus amigos y regresar a casa.",
    estado: "Nuevo",
    ubicacion: "Los Angeles, Estados Unidos",
    fecha_publicacion: "Junio 1995",
    editorial: "Disney Press",
    paginas: 32,
    dimensiones: "8.5 x 0.5 x 11 pulgadas",
    peso: "11.2 onzas"
},
{

    titulo: "La Cenicienta",
    autor: "Charles Perrault",
    genero: "Ficción",
    idioma: "Español",
    precio: 9.50,
    formato: "Tapa dura",
    isbn: "9788482983637",
    descripcion: "La historia de Cenicienta, una joven que encuentra su verdadero amor con la ayuda de un hada madrina.",
    estado: "Nuevo",
    ubicacion: "París, Francia",
    fecha_publicacion: "1697",
    editorial: "Disney Press",
    paginas: 64,
    dimensiones: "8.5 x 0.5 x 11 pulgadas",
    peso: "1.1 libras",
},
 {

    titulo: "Bambi",
    autor: "Felix Salten",
    genero: "Ficción",
    idioma: "Español",
    precio: 11.99,
    formato: "Tapa dura",
    isbn: "9781484721626",
    descripcion: "La historia de Bambi, un cervatillo que enfrenta los desafíos de la vida en el bosque.",
    estado: "Nuevo",
    ubicacion: "Viena, Austria",
    fecha_publicacion: "1923",
    editorial: "Disney Press",
    paginas: 72,
    dimensiones: "8.5 x 0.5 x 11 pulgadas",
    peso: "1.2 libras"
},
 {

    titulo: "Peter Pan",
    autor: "J.M. Barrie",
    genero: "Ficción",
    idioma: "Español",
    precio: 13.99,
    formato: "Tapa dura",
    isbn: "9788427920223",
    descripcion: "La historia de Peter Pan, el niño que nunca crece, y sus aventuras en el País de Nunca Jamás.",
    estado: "Nuevo",
    ubicacion: "Londres, Inglaterra",
    fecha_publicacion: "Octubre 1911",
    editorial: "Disney Press",
    paginas: 176,
    dimensiones: "8.5 x 0.8 x 11 pulgadas",
    peso: "1.8 libras"
    
},
{
    titulo: "Blanca Nieves y los Siete Enanitos",
    autor: "Hermanos Grimm",
    genero: "Ficción",
    idioma: "Español",
    precio: 11.50,
    formato: "Tapa dura",
    isbn: "9788498018244",
    descripcion: "La historia de Blanca Nieves, una joven princesa perseguida por su malvada madrastra.",
    estado: "Nuevo",
    ubicacion: "Berlín, Alemania",
    fecha_publicacion: "1812",
    editorial: "Disney Press",
    paginas: 64,
    dimensiones: "8.5 x 0.5 x 11 pulgadas",
    peso: "1.3 libras"
},
{
    titulo: "Toy Story",
    autor: "Walt Disney Company",
    genero: "Ficción",
    idioma: "Español",
    precio: 13.99,
    formato: "Tapa blanda",
    isbn: "9788499515151",
    descripcion: "La historia de los juguetes de Andy, que cobran vida cuando él no está mirando.",
    estado: "Nuevo",
    ubicacion: "Los Angeles, Estados Unidos",
    fecha_publicacion: "Noviembre 1995",
    editorial: "Editorial Planeta",
    paginas: 48,
    dimensiones: "8 x 0.3 x 8 pulgadas",
    peso: "8.8 onzas"
},
{
    titulo: "Aladdin",
    autor: "Walt Disney Company",
    genero: "Ficción",
    idioma: "Español",
    precio: 12.75,
    formato: "Tapa blanda",
    isbn: "9788427931069",
    descripcion: "La historia de Aladdín, un joven pobre que encuentra una lámpara mágica.",
    estado: "Nuevo",
    ubicacion: "Agrabah, Reino de Arabia",
    fecha_publicacion: "Noviembre 1992",
    editorial: "Editorial Molino",
    paginas: 48,
    dimensiones: "7.5 x 0.3 x 9 pulgadas",
    peso: "6.4 onzas"
},
{
    titulo: "La Cenicienta",
    autor: "Charles Perrault",
    genero: "Ficción",
    idioma: "Español",
    precio: 10.99,
    formato: "Tapa dura",
    isbn: "9780307591944",
    descripcion: "La historia de Cenicienta, una joven que es maltratada por su madrastra y hermanastras.",
    estado: "Nuevo",
    ubicacion: "París, Francia",
    fecha_publicacion: "1697",
    editorial: "Disney Press",
    paginas: 64,
    dimensiones: "9.5 x 0.5 x 12 pulgadas",
    peso: "1.2 libras"
},
{
    titulo: "Moana",
    autor: "Walt Disney Company",
    genero: "Ficción",
    idioma: "Español",
    precio: 11.99,
    formato: "Tapa dura",
    isbn: "9788416917232",
    descripcion: "La historia de Moana, una joven que emprende un viaje para salvar a su isla.",
    estado: "Nuevo",
    ubicacion: "Islas del Sur del Pacífico",
    fecha_publicacion: "Noviembre 2016",
    editorial: "Disney Press",
    paginas: 64,
    dimensiones: "9 x 0.5 x 12 pulgadas",
    peso: "1.4 libras"
},
{
    titulo: "Pinocho",
    autor: "Carlo Collodi",
    genero: "Ficción",
    idioma: "Español",
    precio: 10.50,
    formato: "Tapa blanda",
    isbn: "9788492691258",
    descripcion: "La historia de Pinocho, un muñeco de madera que desea convertirse en un niño real.",
    estado: "Nuevo",
    ubicacion: "Florencia, Italia",
    fecha_publicacion: "1883",
    editorial: "Disney Press",
    paginas: 48,
    dimensiones: "8.5 x 0.3 x 11 pulgadas",
    peso: "14.1 onzas"
},
{
    titulo: "Peter Pan",
    autor: "J.M. Barrie",
    genero: "Ficción",
    idioma: "Español",
    precio: 11.25,
    formato: "Tapa dura",
    isbn: "9788484608657",
    descripcion: "La historia de Peter Pan, un niño que nunca crece y su viaje a la Tierra de Nunca Jamás.",
    estado: "Nuevo",
    ubicacion: "Londres, Inglaterra",
    fecha_publicacion: "Octubre 1911",
    editorial: "Disney Press",
    paginas: 56,
    dimensiones: "9 x 0.5 x 11 pulgadas",
    peso: "1.3 libras"
},
{
     itulo: "Bambi",
    autor: "Felix Salten",
    genero: "Ficción",
    idioma: "Español",
    precio: 10.99,
    formato: "Tapa blanda",
    isbn: "9788499514284",
    descripcion: "La historia de Bambi, un joven ciervo que aprende sobre la vida en el bosque.",
    estado: "Nuevo",
    ubicacion: "Viena, Austria",
    fecha_publicacion: "1923",
    editorial: "Disney Press",
    paginas: 48,
    dimensiones: "8 x 0.3 x 8 pulgadas",
    peso: "8.8 onzas"
},
{
    titulo: "La Bella Durmiente",
    autor: "Charles Perrault",
    genero: "Ficción",
    idioma: "Español",
    precio: 12.75,
    formato: "Tapa dura",
    isbn: "9780307592064",
    descripcion: "La historia de la princesa Aurora, quien cae en un sueño profundo por una maldición.",
    estado: "Nuevo",
    ubicacion: "París, Francia",
    fecha_publicacion: "1697",
    editorial: "Disney Press",
    paginas: 64,
    dimensiones: "9.5 x 0.5 x 12 pulgadas",
    peso: "1.2 libras"
},
{
    titulo: "Hércules",
    autor: "Walt Disney Company",
    genero: "Ficción",
    idioma: "Español",
    precio: 11.99,
    formato: "Tapa blanda",
    isbn: "9788416917218",
    descripcion: "La historia de Hércules, un semidiós que lucha por demostrar su valentía y convertirse en un héroe.",
    estado: "Nuevo",
    ubicacion: "Grecia Antigua",
    fecha_publicacion: "Junio 1997",
    editorial: "Disney Press",
    paginas: 64,
    dimensiones: "8.5 x 0.3 x 11 pulgadas",
    peso: "1.1 libras"
},
]









